# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 14:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=b'', max_length=255)),
                ('link', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('image_link', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=b'', max_length=255, unique=True)),
                ('token', models.CharField(blank=True, max_length=15)),
                ('items', models.ManyToManyField(blank=True, to='list.Item')),
            ],
        ),
    ]
