# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='items',
            field=models.ManyToManyField(blank=True, to='list.Item'),
        ),
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
    ]
