# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 11:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20180308_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='link',
            field=models.TextField(validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(blank=True, default=b'', max_length=255, unique=True),
        ),
    ]
