# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 11:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_auto_20180308_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_link',
            field=models.TextField(default=False, validators=[django.core.validators.URLValidator()]),
            preserve_default=False,
        ),
    ]
